### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by LavishSwarnkar** [kaustubhsuryakantdeshpande/Kotlin-Playground#1]
2nd closing curly brace should be placed below the first one.

https://github.com/kaustubhsuryakantdeshpande/Kotlin-Playground/blob/586f60ab04343cd923a037a82f57686f39e63d5b/PatternProgramming/pattern1.kt#L19

**Comment by deshkaustubh** [comment]
Formatting corrected 👍🏼
