### ISSUE TITLE
Extra Patterns : P6 Wrong Output

### ISSUE THREAD

**Issue by LavishSwarnkar** [kaustubhsuryakantdeshpande/Kotlin-Playground#11]
Wrong output for lines = 3 :
```
  *
 *  *
*    *
 *  *
  * 
```
Notice that the * in first and last line is not in center.

Also, you are interpreting lines wrongly. When lines = 7, pattern should contain exactly 7 lines.
Note that this pattern supports only odd number of lines starting from 3.

**Comment by deshkaustubh** [comment]
updated to print accordingly please check

**Comment by LavishSwarnkar** [comment]
Cool, your program works. But it is too lengthy, you took 67 lines to achieve this simple pattern. Following is a breakdown of this program : 
![WhatsApp Image 2024-11-02 at 10 15 57 AM](https://github.com/user-attachments/assets/5fb8874b-b248-4519-b2d2-90e9c03023e8)

Using above logic, I was able to write the program for this pattern in just 19 lines!

**Comment by LavishSwarnkar** [comment]
Also, do the variable renaming like P5

**Comment by LavishSwarnkar** [comment]
Incorrect output for lines = 3
![Screenshot 2024-11-02 at 10 24 13 AM](https://github.com/user-attachments/assets/31c03242-1d40-4068-9b03-4fde9e9a6a73)

**Comment by deshkaustubh** [comment]
Updated variable names and added this one as pattern6Alternate in same file.

**Comment by LavishSwarnkar** [comment]
Following two code blocks are exactly the same :
https://github.com/kaustubhsuryakantdeshpande/Kotlin-Playground/blob/7df9f85175b13bb50fa722382a74612ec1648113/PatternProgramming/src/pattern6Alternate.kt#L14-L22
https://github.com/kaustubhsuryakantdeshpande/Kotlin-Playground/blob/7df9f85175b13bb50fa722382a74612ec1648113/PatternProgramming/src/pattern6Alternate.kt#L26-L34
Can we improve here by defining and using the same function?

**Comment by deshkaustubh** [comment]
Done sir please check , [here](https://github.com/kaustubhsuryakantdeshpande/KTP-Playground/blob/master/src/main/kotlin/Pattern%20Programs/pattern6Alternate.kt)
