### ISSUE TITLE
KebabCase issues

### ISSUE THREAD

**Issue by LavishSwarnkar** [kaustubhsuryakantdeshpande/Kotlin-Playground#14]
# 1
## Extra space case not handled
 
Quoting from problem statement : 
- Input : `Old  is  Gold`, output : `old-is-gold` 
	- Notice the extra spaces being removed in the output

Your program does not remove the extra spaces : 

![Screenshot 2024-11-04 at 10 06 24 AM](https://github.com/user-attachments/assets/f699ca69-c16e-440f-b47e-4a2d46ae8245)

---

# 2
## Double iteration
In your apprach, the string is being iterated over twice. No major issue as such, but can do it in single iteration? 

Iteration 1 : 

https://github.com/kaustubhsuryakantdeshpande/Kotlin-Playground/blob/7df9f85175b13bb50fa722382a74612ec1648113/EP4AssignmentPrograms/src/main/kotlin/kebabCase.kt#L16

Iteration 2 : 

https://github.com/kaustubhsuryakantdeshpande/Kotlin-Playground/blob/7df9f85175b13bb50fa722382a74612ec1648113/EP4AssignmentPrograms/src/main/kotlin/kebabCase.kt#L4

Can you try to do it in single iteration?

**Comment by deshkaustubh** [comment]
Done Sir 👍🏼, please check

**Comment by deshkaustubh** [comment]
[here](https://github.com/kaustubhsuryakantdeshpande/KTP-Playground/blob/master/src/main/kotlin/EP4ext/kebabCase.kt)

**Comment by LavishSwarnkar** [comment]
# 1
## Not using buildString()
Use buildString() instead of direct string concatenation : 

https://github.com/kaustubhsuryakantdeshpande/KTP-Playground/blob/475b4ccca983b08942d1e9ba9ebe2b4fa6a56c69/src/main/kotlin/EP4ext/kebabCase.kt#L30-L44

---

# 2 (Optional)
## Not a serious issue, but better if you can solve it
- convertToLowercaseAndTrimSpace() function is doing two things (lowercase, removing spaces) in the same function. 
- Ideally a function should do only one thing.
- I would suggest shifting the remove space logic to convertToKebabCase() function.
- And still, the string is being iterated twice. Instead of converting entire string to lowercase in one go, you can use convert char to lowercase function in convertToKebabCase() function directly.
- Try to iterate the string just once.

**Comment by deshkaustubh** [comment]
* [1](https://github.com/kaustubhsuryakantdeshpande/KTP-Playground/blob/master/src/main/kotlin/EP4ext/kebabCase.kt)
* [2](https://github.com/kaustubhsuryakantdeshpande/KTP-Playground/blob/master/src/main/kotlin/EP4ext/kebabCaseAlternate.kt)
