### ISSUE TITLE
parseDigit() : isInteger() check

### ISSUE THREAD

**Issue by LavishSwarnkar** [kaustubhsuryakantdeshpande/Kotlin-Playground#15]
I appreciate that you took time to write this function : 

https://github.com/kaustubhsuryakantdeshpande/Kotlin-Playground/blob/7df9f85175b13bb50fa722382a74612ec1648113/EP4AssignmentPrograms/src/main/kotlin/parseDigit.kt#L20

But actually this function is not required. parseDigit() always returns an Int and you are always passing Int in the isInteger() function. So, 'not Int' case will never get executed. Hence the function is not required.

https://github.com/kaustubhsuryakantdeshpande/Kotlin-Playground/blob/7df9f85175b13bb50fa722382a74612ec1648113/EP4AssignmentPrograms/src/main/kotlin/parseDigit.kt#L2-L4

Here result is always an Int!

**Comment by deshkaustubh** [comment]
Updated Sir 👍🏼, please check

**Comment by deshkaustubh** [comment]
[here](https://github.com/kaustubhsuryakantdeshpande/KTP-Playground/blob/master/src/main/kotlin/EP4ext/parseDigit.kt)
