### ISSUE TITLE
Wrong project structure

### ISSUE THREAD

**Issue by LavishSwarnkar** [kaustubhsuryakantdeshpande/Kotlin-Playground#2]
- All .kt code files must belong inside the src the folder.
- No gradle file found. Project can't run directly on another PC.

**Comment by deshkaustubh** [comment]
Moved the files to src folder, but no idea how the gradle file has to be generated.

**Comment by LavishSwarnkar** [comment]
Which IDE are you using? IntelliJ automatically generates the gradle files.

**Comment by deshkaustubh** [comment]
> Which IDE are you using? IntelliJ automatically generates the gradle files.

I'm using Intellij, no idea what's going wrong
![image](https://github.com/user-attachments/assets/34467735-c1e6-4cbd-b00e-0aab527bcbb2)

**Comment by LavishSwarnkar** [comment]
Ah, I see. It's because you have selected IntelliJ as your build system instead of Gradle.

In the long run, we will use only the Gradle build system that too using Kotlin .kya files.

For this project, it's okay. But when the time comes for adding gradle dependencies, you'll have to use a new project or migrate this one.
