### ISSUE TITLE
if-else formatting

### ISSUE THREAD

**Issue by LavishSwarnkar** [kaustubhsuryakantdeshpande/Kotlin-Playground#3]
https://github.com/kaustubhsuryakantdeshpande/Kotlin-Playground/blob/586f60ab04343cd923a037a82f57686f39e63d5b/PatternProgramming/pattern2.kt#L20-L21

Use either of these correct format :
A.
```kotlin
print(if(j %2 == 0) "*" else "!") 
```
B.
```kotlin
if(j %2 == 0) print("*") else print("!") 
```
c.
```kotlin
if(j %2 == 0)
    print("*")
else 
    print("!") 
```
D.
```kotlin
if(j %2 == 0) {
    print("*")
} else {
    print("!") 
}
```

**Comment by deshkaustubh** [comment]
Chose formatting A, corrected the formatting
