### ISSUE TITLE
Extra Patterns : P3 - Wrong output

### ISSUE THREAD

**Issue by LavishSwarnkar** [kaustubhsuryakantdeshpande/Kotlin-Playground#4]
Wrong output :
![Screenshot_20241028_063251_Kotlin Compiler Offline](https://github.com/user-attachments/assets/16dddb78-5eef-460d-bc0b-dd4d28a8a7a3)

Also, variable is not defined, val keyword missing :
https://github.com/kaustubhsuryakantdeshpande/Kotlin-Playground/blob/586f60ab04343cd923a037a82f57686f39e63d5b/PatternProgramming/pattern3.kt#L28

**Comment by deshkaustubh** [comment]
Corrected the program to display correct output.
