### ISSUE TITLE
Simplify Boolean expression based return statement 

### ISSUE THREAD

**Issue by LavishSwarnkar** [kaustubhsuryakantdeshpande/Kotlin-Playground#5]
https://github.com/kaustubhsuryakantdeshpande/Kotlin-Playground/blob/d95e4700082dd9ba20961a5fdeffd871796df3d2/EP4AssignmentPrograms/src/main/kotlin/EP4Assignment3/EP4Assignment3part1.kt#L20

This can be rewritten in a concise way like this :
`return sum == number`

Same here also :
https://github.com/kaustubhsuryakantdeshpande/Kotlin-Playground/blob/d95e4700082dd9ba20961a5fdeffd871796df3d2/EP4AssignmentPrograms/src/main/kotlin/EP4Assignment3/EP4Assignment3part2.kt#L21

**Comment by deshkaustubh** [comment]
Noted, and updated 👍🏼
