### ISSUE TITLE
Incorrect Automorphic number logic

### ISSUE THREAD

**Issue by LavishSwarnkar** [kaustubhsuryakantdeshpande/Kotlin-Playground#6]
https://github.com/kaustubhsuryakantdeshpande/Kotlin-Playground/blob/d95e4700082dd9ba20961a5fdeffd871796df3d2/EP4AssignmentPrograms/src/main/kotlin/EP4Assignment3/EP4Assignment3part3.kt#L17-L23

Here checking just the last digit is not sufficient. You'll have to check all the digits of the smaller number with the ending digits of it's square.

**Comment by deshkaustubh** [comment]
Got it, I misinterpreted question

**Comment by deshkaustubh** [comment]
Corrected the program please review it.

**Comment by LavishSwarnkar** [comment]
Use of library functions i.e. pow() is not allowed for now.

https://github.com/kaustubhsuryakantdeshpande/Kotlin-Playground/blob/0c6496b5370fc9169ab96b43f6ee336313bf3981/EP4AssignmentPrograms/src/main/kotlin/EP4Assignment3/EP4Assignment3part3.kt#L23

**Comment by deshkaustubh** [comment]
Done sir, please review it once again
