### ISSUE TITLE
Ep4.Ext Special Numbers - missing upTo param based output

### ISSUE THREAD

**Issue by LavishSwarnkar** [kaustubhsuryakantdeshpande/Kotlin-Playground#7]
You have just written the functions to check whether a number is special number or not. But next step is still pending.

Kindly follow this :

fun printPerfectNumbers(upTo: Int)
fun printHarshadNumbers(upTo: Int)
fun printAutomorphicNumbers(upTo: Int)

Each of these functions should print the respective type of numbers from 1 to input UpTo.

**Comment by deshkaustubh** [comment]
Added upTo printer to each of it 👍🏼.
