### ISSUE TITLE
AutomorphicNo - minor improvements

### ISSUE THREAD

**Issue by LavishSwarnkar** [kaustubhsuryakantdeshpande/Kotlin-Playground#8]
# noOfDigits
More suitable name for this fun & variable can be noOfDigits :
https://github.com/kaustubhsuryakantdeshpande/Kotlin-Playground/blob/46d2a74752cc57c616c30d2745fe31ce3444cd03/EP4AssignmentPrograms/src/main/kotlin/EP4Assignment3/EP4Assignment3part3.kt#L35
https://github.com/kaustubhsuryakantdeshpande/Kotlin-Playground/blob/46d2a74752cc57c616c30d2745fe31ce3444cd03/EP4AssignmentPrograms/src/main/kotlin/EP4Assignment3/EP4Assignment3part3.kt#L16

# Use Augmented Assignment operators : 
https://github.com/kaustubhsuryakantdeshpande/Kotlin-Playground/blob/46d2a74752cc57c616c30d2745fe31ce3444cd03/EP4AssignmentPrograms/src/main/kotlin/EP4Assignment3/EP4Assignment3part3.kt#L20-L21
can be written as : 
```kotlin
powerDigit -= -1
divisor *= 10
```
Here also : 
https://github.com/kaustubhsuryakantdeshpande/Kotlin-Playground/blob/46d2a74752cc57c616c30d2745fe31ce3444cd03/EP4AssignmentPrograms/src/main/kotlin/EP4Assignment3/EP4Assignment3part3.kt#L39-L40

**Comment by deshkaustubh** [comment]
Added the Changes 👍🏼
